#!/usr/bin/env bash
# Assemble the Emacs package: the Lisp plus both Linux agent binaries,
# as a tar `M-x package-install-file' understands.
#
# The binaries ride along on purpose. Someone who installs the package
# should be able to connect to a server immediately -- no separate
# download step, no network at connect time, and no version skew
# between the client and the agent it bootstraps.
#
#   scripts/package-emacs.sh                    # build binaries, then package
#   scripts/package-emacs.sh --binaries DIR     # use binaries already built
#   scripts/package-emacs.sh --no-binaries      # Lisp only (downloads at run time)
#
# Output: dist/scrutiny-agent-<version>.tar (+ .sha256)
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUT="${ROOT}/dist"
BINDIR=""
WITH_BINARIES=1

VERSION="$(sed -n 's/^project(scrutiny-agent VERSION \([0-9.]*\).*/\1/p' \
    "${ROOT}/CMakeLists.txt")"
[ -n "${VERSION}" ] || { echo "error: cannot read the version" >&2; exit 1; }

while [ $# -gt 0 ]; do
    case "$1" in
        --binaries) BINDIR="$2"; shift 2 ;;
        --no-binaries) WITH_BINARIES=0; shift ;;
        --out) OUT="$2"; shift 2 ;;
        --version) VERSION="$2"; shift 2 ;;
        -h|--help) sed -n '2,14p' "$0" | sed 's/^# \{0,1\}//'; exit 0 ;;
        *) echo "unknown argument: $1" >&2; exit 2 ;;
    esac
done

NAME="scrutiny-agent"
STAGE="$(mktemp -d)"
PKG="${STAGE}/${NAME}-${VERSION}"
trap 'rm -rf "${STAGE}"' EXIT
mkdir -p "${PKG}"

echo "==> Packaging ${NAME} ${VERSION}"

# --- Lisp ------------------------------------------------------------
# Test files stay out: they are for developing this package, not for
# using it, and they pull in magit and a built agent.
for f in "${ROOT}"/emacs/*.el; do
    case "$(basename "${f}")" in
        *-tests.el) continue ;;
    esac
    cp "${f}" "${PKG}/"
done
cp "${ROOT}/emacs/README.md" "${PKG}/"
cp "${ROOT}/LICENSE" "${PKG}/" 2>/dev/null || true

# The version in the Lisp names the binaries the client asks for, so it
# has to agree with the release this package is cut from.
sed -i.bak "s/^(defcustom ${NAME}-binary-version \"[^\"]*\"/(defcustom ${NAME}-binary-version \"${VERSION}\"/" \
    "${PKG}/${NAME}.el"
rm -f "${PKG}/${NAME}.el.bak"
grep -q "defcustom ${NAME}-binary-version \"${VERSION}\"" "${PKG}/${NAME}.el" \
    || { echo "error: could not stamp the version into ${NAME}.el" >&2; exit 1; }

# --- binaries --------------------------------------------------------
if [ "${WITH_BINARIES}" -eq 1 ]; then
    if [ -z "${BINDIR}" ]; then
        BINDIR="${ROOT}/docker/dist"
        if [ ! -f "${BINDIR}/${NAME}-${VERSION}-x86_64" ] ||
           [ ! -f "${BINDIR}/${NAME}-${VERSION}-aarch64" ]; then
            echo "==> Building both architectures first"
            AGENT_VERSION="${VERSION}" "${ROOT}/scripts/build-agents.sh" \
                --no-install
        fi
    fi
    mkdir -p "${PKG}/bin"
    missing=0
    for arch in x86_64 aarch64; do
        src="${BINDIR}/${NAME}-${VERSION}-${arch}"
        if [ -f "${src}" ]; then
            cp "${src}" "${PKG}/bin/"
            [ -f "${src}.sha256" ] && cp "${src}.sha256" "${PKG}/bin/"
        else
            echo "    warning: no binary for ${arch} at ${src}" >&2
            missing=1
        fi
    done
    if [ "${missing}" -eq 1 ]; then
        echo "    the package will fall back to downloading the missing arch" >&2
    fi
fi

# --- package metadata ------------------------------------------------
# package.el needs this for a multi-file package; without it the tar
# installs but Emacs cannot tell what it is.
cat > "${PKG}/${NAME}-pkg.el" <<EOF
;;; ${NAME}-pkg.el --- package metadata  -*- no-byte-compile: t -*-
;; Generated by scripts/package-emacs.sh -- do not edit.
;;
;; \`define-package' is obsolete from Emacs 29, which reads a
;; single-file package's headers instead -- but a MULTI-file package
;; still needs this file on Emacs 28. no-byte-compile keeps the
;; obsolescence warning out of the installation log.
(define-package "${NAME}" "${VERSION}"
  "Fast remote development over one connection"
  '((emacs "29.1"))
  :url "https://github.com/lally/scrutiny-agent"
  :keywords '("tools" "files" "vc" "processes"))
EOF

cat > "${PKG}/INSTALL.md" <<EOF
# scrutiny-agent ${VERSION} for Emacs

    M-x package-install-file RET scrutiny-agent-${VERSION}.tar RET

Then, in your init:

    (require 'scrutiny-agent-remote)
    (scrutiny-agent-remote-setup
     '(("devbox" :transport "tsh ssh devbox" :roots ("src"))))

The Linux agent binaries for x86_64 and aarch64 ship in \`bin/' inside
this package, so the first connect needs no network: the client picks
the one matching the architecture it probes on the remote, streams it
over your existing transport, verifies it runs, and starts talking to
it.

See README.md for what you get and how to check it is working.
EOF

# --- tar -------------------------------------------------------------
mkdir -p "${OUT}"
TARBALL="${OUT}/${NAME}-${VERSION}.tar"
# package.el requires exactly one top-level directory named NAME-VERSION.
tar -C "${STAGE}" -cf "${TARBALL}" "${NAME}-${VERSION}"

if command -v sha256sum >/dev/null 2>&1; then
    ( cd "${OUT}" && sha256sum "$(basename "${TARBALL}")" | awk '{print $1}' \
        > "${TARBALL}.sha256" )
else
    ( cd "${OUT}" && shasum -a 256 "$(basename "${TARBALL}")" \
        | awk '{print $1}' > "${TARBALL}.sha256" )
fi

echo ""
echo "==> ${TARBALL}"
tar -tf "${TARBALL}" | sed 's/^/    /'
echo ""
echo "    $(du -h "${TARBALL}" | cut -f1)  sha256 $(cat "${TARBALL}.sha256")"
echo ""
echo "Install with:  M-x package-install-file RET ${TARBALL} RET"
