#pragma once
// Workspace preparation for language servers ("try harder").
//
// A language server that starts fine but knows nothing about the
// project answers "running" and returns nothing: clangd without a
// compile database only sees the current translation unit;
// sourcekit-lsp for an Xcode project has no index unless it is told
// where Xcode keeps it. This module discovers (or generates) that
// project configuration before the server starts and reports what it
// found so the UI can say *why* results are thin instead of showing an
// empty panel. Pure path/filesystem logic; no server I/O. Unit-tested.

#include <nlohmann/json.hpp>
#include <optional>
#include <string>
#include <vector>

namespace gitreview::lsp {

enum class Language;  // defined in lsp/LSPClient.hpp (which includes this header)

struct WorkspaceInfo {
    Language language{};  // Language::Unknown (enum is opaque here; defined in LSPClient.hpp)
    std::string workspacePath;
    /// Extra arguments passed to the server because of what was found.
    std::vector<std::string> serverArguments;
    /// C/C++: directory holding compile_commands.json, if any.
    std::optional<std::string> compileCommandsDir;
    /// Swift (Xcode project): the DerivedData index store handed to
    /// sourcekit-lsp, if any.
    std::optional<std::string> indexStorePath;
    /// How the project configuration was obtained: "found", "generated",
    /// "package" (SwiftPM, server self-configures), "none".
    std::string source = "none";
    /// True when the server can be expected to answer cross-file
    /// questions (references, definitions in other files).
    bool crossFileCapable = false;
    /// Human-readable notes: what is missing and how to fix it.
    std::vector<std::string> notes;

    nlohmann::json toJson() const;
};

/// C/C++: look for an existing compile database under the workspace:
/// `<ws>/compile_commands.json`, then any `<ws>/<dir>/compile_commands.json`
/// one level down (build, build-*, cmake-build-*, out, ...). Returns the
/// directory containing it.
std::optional<std::string> findCompileCommandsDir(const std::string& workspacePath);

/// C/C++: directories one level down that hold a configured CMake build
/// (`CMakeCache.txt`) but no compile database yet. Re-running cmake on
/// such a directory with CMAKE_EXPORT_COMPILE_COMMANDS=ON is cheap (the
/// cache already holds the toolchain and options) and produces one.
std::vector<std::string> findConfiguredCMakeBuildDirs(const std::string& workspacePath);

/// True when the workspace root has a CMakeLists.txt.
bool hasCMakeProject(const std::string& workspacePath);

/// Where a compile database generated by us lives for a workspace that
/// has no build directory at all: inside `.git/lsp-cache` (ignored by
/// git, per-clone), or `<ws>/.scrutiny-lsp` without a .git.
std::string generatedCompileDbDir(const std::string& workspacePath);

/// Swift: an `.xcodeproj` / `.xcworkspace` directly under the workspace,
/// preferring a workspace. Nullopt for a SwiftPM-only tree.
std::optional<std::string> findXcodeContainer(const std::string& workspacePath);

/// Swift (macOS): the DerivedData index store for `container` (an
/// .xcodeproj/.xcworkspace path), located by matching `WorkspacePath` in
/// each `<DerivedData>/<Project-hash>/info.plist`. `derivedDataRoot`
/// defaults to ~/Library/Developer/Xcode/DerivedData. Returns the
/// `Index.noindex/DataStore` (or older `Index/DataStore`) directory.
std::optional<std::string> findXcodeIndexStore(const std::string& container,
                                               const std::string& derivedDataRoot = "");

/// Parse the `WorkspacePath` value out of an Xcode info.plist (XML).
/// Exposed for tests.
std::optional<std::string> workspacePathFromInfoPlist(const std::string& plistXml);

/// Run the whole discovery for a language, optionally generating a
/// compile database (runs cmake; bounded by `generateTimeoutSeconds`,
/// 0 disables generation). Never throws; everything it could not do
/// becomes a note.
WorkspaceInfo prepareWorkspace(const std::string& workspacePath, Language language,
                               int generateTimeoutSeconds = 60);

}  // namespace gitreview::lsp
